### ISSUE TITLE
Enable game JSON files to configure headings and section types

### ISSUE THREAD

**Issue by benlk** [oslerw/drinking-game#15]
From #14:

> We could make those lists much more dynamic than they already are, and have the JSON files specify the titles, positions, and layouts of the lists themselves. That would allow us to do the tweaking to make it feel right without introducing a special case.

The current spec looks like this:

```json
{
    "id": "2016-10-19-presidential",
    "title": "October 19th 2016 Presidential Debate",
    "checklist": [
        "string"
    ],
    "everytime": {
        "actions": [
            "string",
        ],
        "phrases": [
            "string"
        ],
        "shots": [
            "string",
        ]
    }
}
```

What we could do is maybe something like this:
- the indices on the "sections" array are the HTML `id`s for the section, 
- "counter" specifies which summation counter to increment.
- "type" explains which partial to load for the forms/labels for each item, be it a checkbox or a +- box or something else entirely (yay options for expansion!)
- "prompts" contains the actual words that display.

```json
{
    "id": "2016-10-19-presidential",
    "title": "October 19th 2016 Presidential Debate",
    "schema": "2",
    "sections": {
        "firsts": {
            "counter": "Shots",
            "type": "checkbox",
            "heading": "Drink the first time",
            "prompts": [
                "string",
                "string",
                "string",
            ],
        },
        "actions": {
            "counter": "Drinks",
            "type": "counter",
            "heading": "Everytime a candidate:",
            "prompts": [
                "string",
                "string",
                "string",
            ],
        },
        "phrases": {
            "counter": "Drinks",
            "type": "counter",
            "heading": "Everytime a candidate says:",
            "prompts": [
                "string",
                "string",
                "string",
            ],
        },
        "shots": {
            "counter": "Shots",
            "type": "counter",
            "heading": "Take a shot if:",
            "prompts": [
                "string",
                "string",
                "string",
            ],
        }
    },
}
```

**Comment by oslerw** [comment]
For now this is kind of done, -ish. I think I like some things from your format much better, but it's going to involve even more refactoring of the internals (which is badly needed anyway). I'm going to keep this in mind and reopen if I ever get back to it.
